use_frameworks!

platform :ios, '10.0'

target 'MSSwiftExtensions_Example' do
  pod 'MSSwiftExtensions', :path => '../'

  target 'MSSwiftExtensions_Tests' do
    inherit! :search_paths

    
  end
end
